adding error action.

diff --git a/.github/Composite-Actions/Fix-Nuget-Feeds/action.yml b/.github/Composite-Actions/Fix-Nuget-Feeds/action.yml
--- a/.github/Composite-Actions/Fix-Nuget-Feeds/action.yml
+++ b/.github/Composite-Actions/Fix-Nuget-Feeds/action.yml
@@ -19,8 +19,9 @@ runs:
   steps:
     - name: Set working directory
       run: cd ${{ github.workspace }}/.github/Composite-Actions/Fix-Nuget-Feeds
-      shell: pwsh
-      
+      shell: |
+        pwsh -noninteractive -command "try { $ErrorActionPreference='Stop'; . '{0}' } catch { Write-Error ""FAILED: $_""; throw; } if ((Test-Path -LiteralPath variable:\LASTEXITCODE)) { exit $LASTEXITCODE }"
+
     - name: Check PowerShell script existence
       run: |
         $scriptPath = ".\powershell\scripts\set-nugetfeeds.ps1"
